/**
 * Browser-safe. Reads the kernel's pre-resolved decisions (generated by
 * scripts/generate-skill-map.ts, which runs runTask() in Node). Never
 * imports ~/.agents/kernel/engine.ts directly here — that file uses
 * fs/path/os and cannot run in a Vite/React bundle.
 */
import resolved from "./resolvedSkills.json";

type ResolvedSkillEntry = { activeSkills: string[]; status: "success" | "empty" | "failure" };

const RESOLVED_SKILLS = resolved as Record<string, ResolvedSkillEntry>;

export function getActiveSkills(task: string): string[] {
  return RESOLVED_SKILLS[task]?.activeSkills ?? [];
}

export function hasSkill(task: string, skillName: string): boolean {
  return getActiveSkills(task).includes(skillName);
}
